### ISSUE TITLE
Salt is used even if Deterministic is disabled

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/defender-deploy-plugin#25]
From Wizard:
1. Enable "Deterministic" and add a salt, for example add an invalid salt like "0x123"
2. Disable "Deterministic"
3. Click "Deploy"

It attempts to deploy with the salt even though "Deterministic" was disabled.  In the above case, this results in an error due to the invalid salt.

![Screenshot 2024-12-11 at 2 27 03 PM](https://github.com/user-attachments/assets/ce84ef47-8041-45e9-b5ea-f9782dc969c8)

This seems to be because `salt` is always passed through [here](https://github.com/OpenZeppelin/defender-deploy-plugin/blob/main/src/lib/wizard/components/Deploy.svelte#L275), which has the last salt that the user entered before disabling "Deterministic".

The same might also apply to Remix.

**Comment by MCarlomagno** [comment]
https://github.com/OpenZeppelin/defender-deploy-plugin/pull/26

**Comment by MCarlomagno** [comment]
Fixed in https://github.com/OpenZeppelin/defender-deploy-plugin/pull/26
